# Generated by Django 4.2.1 on 2023-06-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_profesional_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'Presupuesto'], [1, 'Reclamo']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Profesional',
            new_name='Mecanico',
        ),
    ]
