# Generated by Django 4.2.1 on 2023-06-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0003_contacto_rename_profesional_mecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='foto',
            field=models.ImageField(null=True, upload_to='pagmecanicos'),
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('Modelo', models.TextField()),
                ('categoria', models.IntegerField(choices=[[0, 'Mantencíon de kilometraje'], [1, 'Cambio de aceite'], [2, 'Frenos'], [3, 'Baterías'], [4, 'Scanner y diagnostico'], [5, 'otros']])),
                ('observacion', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
