# Generated by Django 4.2.1 on 2023-06-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_alter_mecanico_foto_atencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='foto',
            new_name='fotografia',
        ),
    ]
