# Generated by Django 4.2.1 on 2023-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_rename_foto_atencion_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='Modelo',
            field=models.CharField(max_length=100),
        ),
    ]
