# Generated by Django 4.2.1 on 2023-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_categoria_alter_mecanico_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='foto',
            field=models.ImageField(null=True, upload_to='pagmecanicos'),
        ),
    ]
