# Generated by Django 4.2.1 on 2023-06-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_alter_atencion_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='Estado',
            field=models.CharField(default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Mantencíon de kilometraje'], [1, 'Cambio de aceite'], [2, 'Frenos'], [3, 'Baterías'], [4, 'Scanner y diagnostico'], [5, 'otros']]),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='categoria'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='foto',
            field=models.ImageField(null=True, upload_to='mecanicos'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
