# Generated by Django 4.2.1 on 2023-06-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_atencion_estado_alter_atencion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='Estado',
            field=models.CharField(default='I', max_length=10),
        ),
    ]
