# Generated by Django 4.2.1 on 2023-06-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_remove_atencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='Estado',
            field=models.CharField(default='I', max_length=10),
        ),
    ]
