# Generated by Django 4.2.1 on 2023-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_atencion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='Estado',
            field=models.IntegerField(default=0),
        ),
    ]
