# Generated by Django 4.2.1 on 2023-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_remove_atencion_id_atencion_id_atencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='id_Atencion',
        ),
        migrations.AddField(
            model_name='atencion',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
