# Generated by Django 4.2.1 on 2023-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0018_categoria_alter_atencion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='id',
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_atencion',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
