# Generated by Django 4.2.1 on 2023-07-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0019_remove_atencion_id_atencion_id_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='id_atencion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
