# Generated by Django 4.2.1 on 2023-07-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0020_alter_atencion_id_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='id_atencion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('cv', models.FileField(upload_to='cv/')),
                ('cargo_postulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appweb.cargo')),
            ],
        ),
    ]
