# Generated by Django 4.2.1 on 2023-07-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0022_remove_postulante_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanico',
            name='id',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='id_atencion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_postulante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
