# Generated by Django 4.2.1 on 2023-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_remove_mecanico_id_mecanico_id_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='Estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
