# Generated by Django 4.2.1 on 2023-07-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0024_alter_atencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='experiencia',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='postulante',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='postulantes'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
