# Generated by Django 4.2.1 on 2023-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0025_postulante_experiencia_postulante_fotografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanico',
            old_name='id_atencion',
            new_name='id_mecanico',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='experiencia',
            field=models.CharField(max_length=100),
        ),
    ]
