# Generated by Django 4.2.1 on 2023-07-08 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0028_alter_mecanico_options_remove_mecanico_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecanico',
            options={},
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
