# Generated by Django 4.2.1 on 2023-07-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0032_mecanico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='rut',
            field=models.CharField(max_length=15),
        ),
    ]
