# Generated by Django 4.2.1 on 2023-07-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0033_alter_mecanico_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='id',
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_contacto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
